DELETE FROM projects;
DELETE FROM testimonials;

INSERT INTO projects (id, slug, title, category, short_description, full_description, challenge, solution, images, before_image, after_image, featured_image, surface, duration, location, year, featured, services) VALUES
('creation-jardin-courpaley', 'creation-jardin-courpaley', 'Création de Jardin à Courpaley', 'jardin', 'Terrain nu transformé en jardin complet : gazon en plaques, clôture composite et finitions.', 'Le client avait un terrain en terre battue, sans rien dessus. On a tout préparé : nivellement, apport de terre végétale, pose de gazon en plaques pour un résultat immédiat. On a terminé par une clôture composite anthracite tout autour.', 'Sol très compact, pas de végétation du tout. Il fallait tout reprendre de zéro.', 'On a retourné le sol, apporté du terreau, posé le gazon en plaques et installé la clôture sur fondations béton. Résultat propre en 2 semaines.', ARRAY['/images/_template/portfolio/apres/projet-1-apres.jpg', '/images/_template/portfolio/apres/projet-2-apres.jpg', '/images/_template/portfolio/apres/projet-3-apres.jpg'], '/images/_template/portfolio/avant/projet-1-avant.jpg', '/images/_template/portfolio/apres/projet-1-apres.jpg', '/images/_template/portfolio/apres/projet-1-apres.jpg', '250 m²', '2 semaines', 'Courpaley', 2025, true, ARRAY['creation-jardins']),
('terrasse-travertin-nangis', 'terrasse-travertin-nangis', 'Terrasse en Travertin à Nangis', 'terrasse', 'Pose de travertin autour d''une piscine avec taille de haies et nettoyage complet.', 'Les abords de la piscine étaient vieillissants, les haies partaient dans tous les sens. On a posé du travertin ivoire sur dalle stabilisée, taillé toutes les haies bien droit, et nettoyé l''ensemble.', 'Ancien dallage abîmé, haies pas entretenues depuis longtemps.', 'Dépose de l''ancien revêtement, pose du travertin, taille de toutes les haies et nettoyage haute pression.', ARRAY['/images/_template/portfolio/apres/projet-2-apres.jpg', '/images/_template/portfolio/apres/projet-3-apres.jpg'], '/images/_template/portfolio/avant/projet-2-avant.jpg', '/images/_template/portfolio/apres/projet-2-apres.jpg', '/images/_template/portfolio/apres/projet-2-apres.jpg', '80 m²', '3 semaines', 'Nangis', 2025, true, ARRAY['amenagement-terrasses']),
('allee-amenagee-noisy', 'allee-amenagee-noisy-le-grand', 'Allée Aménagée à Noisy-le-Grand', 'terrasse', 'Réfection complète d''une allée d''entrée : bordures, gravier stabilisé et désherbage.', 'L''allée était en mauvais état : béton fissuré, mauvaises herbes partout, bordures cassées. On a tout repris : nouvelles bordures béton, gravier stabilisé, et désherbage complet des abords.', 'Allée étroite le long de la façade, envahie par les mauvaises herbes.', 'Désherbage manuel, pose de bordures neuves, gravier stabilisé et paillage minéral pour éviter que ça repousse.', ARRAY['/images/_template/portfolio/apres/projet-3-apres.jpg', '/images/_template/portfolio/apres/projet-4-apres.jpg'], '/images/_template/portfolio/avant/projet-3-avant.jpg', '/images/_template/portfolio/apres/projet-3-apres.jpg', '/images/_template/portfolio/apres/projet-3-apres.jpg', '30 m²', '1 semaine', 'Noisy-le-Grand', 2025, true, ARRAY['creation-jardins', 'amenagement-terrasses']),
('cloture-composite-provins', 'cloture-composite-provins', 'Clôture Composite à Provins', 'cloture', 'Pose de clôture composite anthracite avec remise en état du jardin.', 'Le jardin était en friche totale : herbes hautes, pas de clôture, terrain bosselé. On a tout débroussaillé, nivelé, posé des panneaux composites anthracite et fini par du gazon.', 'Terrain en friche complète, pas de délimitation de propriété.', 'Débroussaillage, nivellement, pose des poteaux et panneaux sur fondations béton, gazon et finitions.', ARRAY['/images/_template/portfolio/apres/projet-4-apres.jpg'], '/images/_template/portfolio/avant/projet-4-avant.jpg', '/images/_template/portfolio/apres/projet-4-apres.jpg', '/images/_template/portfolio/apres/projet-4-apres.jpg', '35 ml', '2 semaines', 'Provins', 2025, false, ARRAY['clotures-murets']),
('elagage-grands-arbres-melun', 'elagage-grands-arbres-melun', 'Élagage de Grands Arbres à Melun', 'elagage', 'Élagage en hauteur et abattage d''arbres dangereux chez un particulier.', 'Plusieurs grands arbres menaçaient la maison et les lignes électriques. On est intervenu en grimpe pour tailler, réduire et abattre les arbres les plus dangereux.', 'Arbres très hauts, proches de la maison et des câbles. Pas de place pour un engin.', 'Élagage en grimpe avec harnais et cordes, démontage branche par branche. Broyage sur place.', ARRAY['/images/_template/portfolio/apres/projet-5-apres.jpg'], '/images/_template/portfolio/avant/projet-5-avant.jpg', '/images/_template/portfolio/apres/projet-5-apres.jpg', '/images/_template/portfolio/apres/projet-5-apres.jpg', '500 m²', '3 jours', 'Melun', 2025, false, ARRAY['elagage']),
('amenagement-complet-fontenay', 'amenagement-complet-fontenay-tresigny', 'Aménagement Complet à Fontenay-Trésigny', 'amenagement-complet', 'Reprise totale d''une propriété : débroussaillage, pelouse, haies et clôtures.', 'La propriété était à l''abandon depuis des années : ronces, herbes hautes partout. On a tout repris : débroussaillage, évacuation, préparation du sol, semis de gazon, taille des haies et tonte de finition.', 'Terrain complètement envahi. Ronces et herbes hautes rendaient l''espace impraticable.', 'Débroussaillage mécanique, évacuation des déchets, préparation du sol, semis et tonte. Résultat : une pelouse nette.', ARRAY['/images/_template/portfolio/apres/projet-6-apres.jpg', '/images/_template/portfolio/apres/projet-1-apres.jpg', '/images/_template/portfolio/apres/projet-2-apres.jpg'], '/images/_template/portfolio/avant/projet-6-avant.jpg', '/images/_template/portfolio/apres/projet-6-apres.jpg', '/images/_template/portfolio/apres/projet-6-apres.jpg', '1000 m²', '4 semaines', 'Fontenay-Trésigny', 2025, true, ARRAY['creation-jardins', 'amenagement-terrasses', 'clotures-murets']);

INSERT INTO testimonials (id, client_name, client_role, quote, rating, project_type, date) VALUES
('1', 'Marie Dubois', 'Propriétaire à Courpaley', 'Ethan a refait tout notre jardin, gazon et clôture compris. Le travail est nickel, propre, et il a fini dans les temps. On recommande les yeux fermés.', 5, 'Création de jardin', '2024-06'),
('2', 'Famille Martin', 'Propriétaires à Nangis', 'Super boulot sur notre terrasse. L''équipe est sérieuse, ponctuelle, et le résultat est top. Rien à redire.', 5, 'Terrasse', '2024-03'),
('3', 'M. Rousseau', 'Propriétaire à Provins', 'Ils ont tout refait chez nous : pelouse, haies, allée. Chantier propre, bien géré, et dans le budget annoncé. Très satisfait.', 5, 'Aménagement complet', '2024-08');

UPDATE services SET short_description = 'On crée votre jardin de A à Z : préparation du terrain, gazon, plantations. Tout est fait sur mesure.', full_description = 'Vous partez d''un terrain vide ou d''un jardin qui ne vous plaît plus ? On s''en occupe. On prépare le sol, on pose le gazon, on plante ce qu''il faut et on installe les clôtures si besoin.', features = ARRAY['Étude de votre terrain sur place', 'Préparation du sol et nivellement', 'Pose de gazon en plaques ou semis', 'Plantations adaptées à votre sol', 'Suivi après plantation'] WHERE id = 'creation-jardins';
UPDATE services SET short_description = 'Terrasses en pierre, bois ou dalles, allées et bordures. On aménage vos extérieurs pour en profiter vraiment.', full_description = 'On pose des terrasses en travertin, en bois, en dalles béton — selon vos goûts et votre budget. On fait aussi les allées, les bordures, les marches.', features = ARRAY['Terrasses en pierre, bois ou dalles', 'Allées et bordures', 'Pose sur dalle stabilisée', 'Drainage intégré', 'Garantie décennale'] WHERE id = 'amenagement-terrasses';
UPDATE services SET short_description = 'Tonte, taille de haies, désherbage, nettoyage. On entretient votre jardin toute l''année.', full_description = 'Un jardin, ça s''entretient. On passe régulièrement pour tondre, tailler les haies, désherber les massifs et nettoyer. Contrat à l''année ou ponctuel.', features = ARRAY['Tonte régulière', 'Taille de haies et arbustes', 'Désherbage des massifs', 'Nettoyage saisonnier', 'Contrats à l''année possibles'] WHERE id = 'entretien-paysager';
UPDATE services SET short_description = 'Élagage, abattage, taille d''arbres et d''arbustes. On intervient en toute sécurité, même en hauteur.', full_description = 'Vos arbres sont trop hauts, mal en point, ou trop proches de la maison ? On intervient en grimpe ou avec nacelle pour élaguer, réduire ou abattre en toute sécurité.', features = ARRAY['Élagage en grimpe', 'Abattage sécurisé', 'Taille de réduction', 'Dessouchage et broyage', 'Évacuation des déchets verts'] WHERE id = 'elagage';
UPDATE services SET short_description = 'Clôtures composite, alu, bois, grillage, murets et portails. On ferme et on sécurise votre terrain.', full_description = 'On pose tous types de clôtures : panneaux composites, aluminium, bois, grillage rigide. On fait aussi les murets, les portails et les portillons.', features = ARRAY['Clôtures composite et aluminium', 'Grillage rigide', 'Murets et bordures', 'Portails et portillons', 'Fondations béton solides'] WHERE id = 'clotures-murets';
UPDATE services SET short_description = 'Installation d''arrosage automatique pour un jardin toujours vert sans y penser.', full_description = 'On installe des systèmes d''arrosage automatique adaptés à votre jardin. Aspersion, goutte-à-goutte, programmateur — tout est réglé pour arroser au bon moment.', features = ARRAY['Étude de votre terrain', 'Aspersion et goutte-à-goutte', 'Programmateur automatique', 'Réglage zone par zone', 'Économie d''eau'] WHERE id = 'arrosage-automatique';
